import type { Metadata } from "next";
import "./globals.css";
import ToastContainer from "@/components/toast/ToastContainer";
import SpinnerOverlay from "@/components/spinner/SpinnerOverlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer />
        <SpinnerOverlay/>
      </body>
    </html>
  );
}
