import type { Metadata } from "next";
import "./globals.css";
import ToastContainer from "@/components/toast/ToastContainer";
import SpinnerOverlay from "@/components/spinner/SpinnerOverlay";
import MainLayout from "@/components/layout/main/MainLayout";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>
        <MainLayout>   
          {children}
          <ToastContainer />
          <SpinnerOverlay/>
         </MainLayout>      
        <Footer/>
      </body>
    </html>
  );
}
