import type { Metadata } from "next";
import "./globals.css";
import ToastContainer from "@/components/toast/ToastContainer";
import SpinnerOverlay from "@/components/spinner/SpinnerOverlay";
import MainLayout from "@/components/layout/main/MainLayout";
import Footer from "@/components/footer/Footer";
import ModalContainer from "@/components/modal/ModalContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <MainLayout>   
          {children}
          <ModalContainer />
          <ToastContainer />
          <SpinnerOverlay/>
         </MainLayout>      
        <Footer/>
      </body>
    </html>
  );
}
